name: Publish
on: [push]

permissions:
  contents: read
  packages: write

jobs:
  push-to-gh-cr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t ghcr.io/atyusan/ghcr-gha:${{ github.sha }} .
      - name: Push Docker image
        run: docker push ghcr.io/atyusan/ghcr-gha:${{ github.sha }}
